spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rules-db'
    username: bishoy
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true